spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: sales-app-backend
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/salesdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
#aws-s3:
#  access-key:
#  secret-key:
#  bucket-name:
cloudinary:
  name: drbheeyyb
  key: 879184449341558
  secret: 0t7Evh6H2t9946HjWQlWv7_1dR8